# Generated by Django 3.2.4 on 2021-06-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='real_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Real time'),
        ),
    ]
