# Generated by Django 3.2.4 on 2021-06-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='total_duration',
        ),
    ]
