# Generated by Django 3.2.4 on 2021-06-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_delete_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_start', models.DateTimeField(auto_now_add=True, verbose_name='Start at:')),
                ('execution_end', models.DateTimeField(auto_now=True, verbose_name='Finish at:')),
                ('real_time', models.TimeField(blank=True, null=True, verbose_name='Average time')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_timer', to='tasks.task', verbose_name='Root task')),
            ],
            options={
                'verbose_name': 'Timer',
                'verbose_name_plural': 'Timers',
            },
        ),
    ]
