# Generated by Django 3.2.4 on 2021-06-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_delete_timer'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Time log',
                'verbose_name_plural': 'Time logs',
            },
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
