# Generated by Django 3.2.4 on 2021-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20210628_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
